from greek_features import *

verse_files_to_exclude = {
	'tesserae/texts/grc/aeschylus.agamemnon.tess',
	'tesserae/texts/grc/aeschylus.eumenides.tess',
	'tesserae/texts/grc/aeschylus.libation_bearers.tess',
	'tesserae/texts/grc/aeschylus.persians.tess',
	'tesserae/texts/grc/aeschylus.prometheus_bound.tess',
	'tesserae/texts/grc/aeschylus.seven_against_thebes.tess',
	'tesserae/texts/grc/aeschylus.suppliant_women.tess',
	'tesserae/texts/grc/apollonius.argonautica.tess',
	'tesserae/texts/grc/apollonius.argonautica/apollonius.argonautica.part.1.tess',
	'tesserae/texts/grc/apollonius.argonautica/apollonius.argonautica.part.2.tess',
	'tesserae/texts/grc/apollonius.argonautica/apollonius.argonautica.part.3.tess',
	'tesserae/texts/grc/apollonius.argonautica/apollonius.argonautica.part.4.tess',
	'tesserae/texts/grc/aristophanes.acharnians.tess',
	'tesserae/texts/grc/aristophanes.birds.tess',
	'tesserae/texts/grc/aristophanes.clouds.tess',
	'tesserae/texts/grc/aristophanes.ecclesiazusae.tess',
	'tesserae/texts/grc/aristophanes.frogs.tess',
	'tesserae/texts/grc/aristophanes.knights.tess',
	'tesserae/texts/grc/aristophanes.lysistrata.tess',
	'tesserae/texts/grc/aristophanes.peace.tess',
	'tesserae/texts/grc/aristophanes.plutus.tess',
	'tesserae/texts/grc/aristophanes.thesmophoriazusae.tess',
	'tesserae/texts/grc/aristophanes.wasps.tess',
	'tesserae/texts/grc/bacchylides.dithyrambs.tess',
	'tesserae/texts/grc/bacchylides.epinicians.tess',
	'tesserae/texts/grc/bion_of_phlossa.epitaphius.tess',
	'tesserae/texts/grc/bion_of_phlossa.epithalamium.tess',
	'tesserae/texts/grc/bion_of_phlossa.fragmenta.tess',
	'tesserae/texts/grc/callimachus.epigrams.tess',
	'tesserae/texts/grc/callimachus.hymns.tess',
	'tesserae/texts/grc/colluthus.rape_of_helen.tess',
	'tesserae/texts/grc/euripides.alcestis.tess',
	'tesserae/texts/grc/euripides.andromache.tess',
	'tesserae/texts/grc/euripides.bacchae.tess',
	'tesserae/texts/grc/euripides.cyclops.tess',
	'tesserae/texts/grc/euripides.electra.tess',
	'tesserae/texts/grc/euripides.hecuba.tess',
	'tesserae/texts/grc/euripides.helen.tess',
	'tesserae/texts/grc/euripides.heracleidae.tess',
	'tesserae/texts/grc/euripides.heracles.tess',
	'tesserae/texts/grc/euripides.hippolytus.tess',
	'tesserae/texts/grc/euripides.ion.tess',
	'tesserae/texts/grc/euripides.iphigenia_aulis.tess',
	'tesserae/texts/grc/euripides.iphigenia_tauris.tess',
	'tesserae/texts/grc/euripides.medea.tess',
	'tesserae/texts/grc/euripides.orestes.tess',
	'tesserae/texts/grc/euripides.phoenissae.tess',
	'tesserae/texts/grc/euripides.rhesus.tess',
	'tesserae/texts/grc/euripides.suppliants.tess',
	'tesserae/texts/grc/euripides.trojan_women.tess',
	'tesserae/texts/grc/homer.iliad.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.1.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.10.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.11.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.12.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.13.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.14.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.15.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.16.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.17.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.18.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.19.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.2.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.20.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.21.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.22.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.23.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.24.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.3.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.4.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.5.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.6.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.7.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.8.tess',
	'tesserae/texts/grc/homer.iliad/homer.iliad.part.9.tess',
	'tesserae/texts/grc/homer.odyssey.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.1.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.10.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.11.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.12.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.13.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.14.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.15.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.16.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.17.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.18.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.19.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.2.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.20.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.21.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.22.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.23.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.24.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.3.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.4.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.5.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.6.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.7.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.8.tess',
	'tesserae/texts/grc/homer.odyssey/homer.odyssey.part.9.tess',
	'tesserae/texts/grc/lucian.podagra.tess',
	'tesserae/texts/grc/lycophron.alexandra.tess',
	'tesserae/texts/grc/nonnus_of_panopolis.dionysiaca.tess',
	'tesserae/texts/grc/nonnus_of_panopolis.dionysiaca/nonnus_of_panopolis.dionysiaca.part.1.books_1-10.tess',
	'tesserae/texts/grc/nonnus_of_panopolis.dionysiaca/nonnus_of_panopolis.dionysiaca.part.2.books_11-20.tess',
	'tesserae/texts/grc/nonnus_of_panopolis.dionysiaca/nonnus_of_panopolis.dionysiaca.part.3.books_21-30.tess',
	'tesserae/texts/grc/nonnus_of_panopolis.dionysiaca/nonnus_of_panopolis.dionysiaca.part.4.books_31-40.tess',
	'tesserae/texts/grc/nonnus_of_panopolis.dionysiaca/nonnus_of_panopolis.dionysiaca.part.5.books_41-48.tess',
	'tesserae/texts/grc/oppian.halieutica.tess',
	'tesserae/texts/grc/oppian.halieutica/oppian.halieutica.part.1.tess',
	'tesserae/texts/grc/oppian.halieutica/oppian.halieutica.part.2.tess',
	'tesserae/texts/grc/oppian.halieutica/oppian.halieutica.part.3.tess',
	'tesserae/texts/grc/oppian.halieutica/oppian.halieutica.part.4.tess',
	'tesserae/texts/grc/oppian.halieutica/oppian.halieutica.part.5.tess',
	'tesserae/texts/grc/oppian_of apamea.cynegetica/oppian_of_apamea.cynegetica.part.1.tess',
	'tesserae/texts/grc/oppian_of apamea.cynegetica/oppian_of_apamea.cynegetica.part.2.tess',
	'tesserae/texts/grc/oppian_of apamea.cynegetica/oppian_of_apamea.cynegetica.part.3.tess',
	'tesserae/texts/grc/oppian_of apamea.cynegetica/oppian_of_apamea.cynegetica.part.4.tess',
	'tesserae/texts/grc/oppian_of_apamea.cynegetica.tess',
	'tesserae/texts/grc/pindar.odes.tess',
	'tesserae/texts/grc/pindar.odes/pindar.odes.part.1.isthmeans.tess',
	'tesserae/texts/grc/pindar.odes/pindar.odes.part.2.nemeans.tess',
	'tesserae/texts/grc/pindar.odes/pindar.odes.part.3.olympians.tess',
	'tesserae/texts/grc/pindar.odes/pindar.odes.part.4.pythians.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.1.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.10.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.11.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.12.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.13.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.14.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.2.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.3.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.4.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.5.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.6.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.7.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.8.tess',
	'tesserae/texts/grc/quintus_smyrnaeus.fall_of_troy/quintus_smyrnaeus.fall_of_troy.part.9.tess',
	'tesserae/texts/grc/sophocles.ajax.tess',
	'tesserae/texts/grc/sophocles.antigone.tess',
	'tesserae/texts/grc/sophocles.electra.tess',
	'tesserae/texts/grc/sophocles.ichneutae.tess',
	'tesserae/texts/grc/sophocles.oedipus_at_colonus.tess',
	'tesserae/texts/grc/sophocles.oedipus_tyrannus.tess',
	'tesserae/texts/grc/sophocles.philoctetes.tess',
	'tesserae/texts/grc/sophocles.trachiniae.tess',
	'tesserae/texts/grc/theocritus.epigrams.tess',
	'tesserae/texts/grc/tryphiodorus.the_taking_of_ilios.tess',
}

if __name__ == '__main__':

	#Download corpus if non-existent
	corpus_dir = join('tesserae', 'texts', 'grc')
	tesserae_clone_command = 'git clone https://github.com/timgianitsos/tesserae.git'
	if not os.path.isdir(corpus_dir):
		print(RED + 'Corpus at ' + corpus_dir + ' does not exist - attempting to clone repository...' + RESET)
		if os.system(tesserae_clone_command) is not 0:
			raise Exception('Unable to obtain corpus for feature extraction')

	#Feature extractions
	extract_features.main(
		corpus_dir, 
		'tess', 

		#Exclude the following directories and files
		excluded_paths=composite_files_to_exclude | verse_files_to_exclude,

		#Only extract the following features
		# features=['freq_men'], 

		#Output the results to a file in order to be processed by machine learning algorithms
		output_file=None if len(sys.argv) <= 1 else sys.argv[1] 
	)
